
require('dotenv').config({ path: '../.env' });
const mongoose = require('mongoose');

const PujaSchema = new mongoose.Schema({
  name: String, description: String, category: String,
  price: Number, duration: String, significance: String,
  whenToPerform: String, benefits: [String], isActive: { type: Boolean, default: true }
}, { timestamps: true });
const Puja = mongoose.model('Puja', PujaSchema);

const pujas = [
  { name: 'Lord Shiva Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Archana is a personal mode of offering your prayers to Lord Shiva performed by temple priests by chanting specific slokas and mantras.', significance: 'Connects devotee directly to Lord Shiva through personalized mantras with name, gothram and birth star.', benefits: ['Removes obstacles and negativity', 'Grants peace and prosperity', 'Spiritual connection with Lord Shiva'] },
  { name: 'Sri Anjaneya Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Personal prayers offered to Lord Anjaneya by chanting specific slokas and mantras by temple priests.', significance: 'Lord Hanuman blesses devotees with strength, courage and removal of evil.', benefits: ['Removes fear and evil', 'Grants strength and courage', 'Protects from negative energies'] },
  { name: 'Sri Vighneswara Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Archana offered to Lord Ganesha the remover of obstacles by chanting Vedic mantras with your name and birth star.', significance: 'Lord Ganesha removes all obstacles and blesses with success.', benefits: ['Removes all obstacles', 'Grants success and wisdom', 'Auspicious beginnings'] },
  { name: 'Sri Shirdi Saibaba Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Personal mode of offering prayers to Sri Shirdi Saibaba through specific slokas and mantras.', significance: 'Sai Baba blesses devotees with peace, health and prosperity.', benefits: ['Peace of mind', 'Health and prosperity', 'Fulfillment of wishes'] },
  { name: 'Sri Durga Devi Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Prayers offered to Goddess Durga by chanting specific Vedic mantras with name, gothram and birth star.', significance: 'Goddess Durga destroys evil and blesses devotees with power and protection.', benefits: ['Protection from evil', 'Grants power and courage', 'Removes negativity'] },
  { name: 'Sri Venkateswara Swamy Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Archana offered to Lord Venkateswara at home with personal mantras chanted by the priest.', significance: 'Lord Venkateswara blesses with wealth, prosperity and moksha.', benefits: ['Wealth and prosperity', 'Removal of sins', 'Moksha and liberation'] },
  { name: 'Sri Krishna Bhagvan Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Personal prayers to Lord Krishna through Vedic slokas and mantras by experienced priests.', significance: 'Lord Krishna blesses devotees with love, wisdom and divine protection.', benefits: ['Divine love and wisdom', 'Protection from evil', 'Spiritual growth'] },
  { name: 'Sri Narasimha Swamy Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Archana to Lord Narasimha the fierce protector form of Lord Vishnu.', significance: 'Lord Narasimha protects devotees from all evil and grants fearlessness.', benefits: ['Protection from all evil', 'Grants fearlessness', 'Removes negative energies'] },
  { name: 'Sri Subrahmanya Swamy Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Prayers offered to Lord Subrahmanya through specific mantras for health and prosperity.', significance: 'Lord Subrahmanya removes Sarpa Dosha and blesses with health.', benefits: ['Removes Sarpa Dosha', 'Grants health and vitality', 'Success in endeavors'] },
  { name: 'Sri Surya Bhagavan Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Archana to Sun God Surya Bhagavan for health and vitality.', significance: 'Sun God blesses with good health, confidence and success.', benefits: ['Good health and vitality', 'Confidence and leadership', 'Success in career'] },
  { name: 'Navagraha Archana', category: 'Archana', price: 701, duration: '1 hour', description: 'Archana to all nine planets simultaneously for removal of planetary doshas.', significance: 'Removes malefic effects of all nine planets simultaneously.', benefits: ['Removes all planetary doshas', 'Harmonizes planetary influences', 'Overall prosperity'] },
  { name: 'Sri Saraswathi Devi Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Prayers to Goddess Saraswathi for wisdom, knowledge and success in studies.', significance: 'Goddess Saraswathi blesses with wisdom, knowledge and excellence.', benefits: ['Success in studies', 'Wisdom and knowledge', 'Excellence in arts'] },
  { name: 'Sri Lakshmi Devi Archana', category: 'Archana', price: 501, duration: '45 mins', description: 'Archana to Goddess Lakshmi for wealth, prosperity and good fortune.', significance: 'Goddess Lakshmi blesses with wealth, prosperity and fortune.', benefits: ['Financial prosperity', 'Good fortune', 'Removes financial obstacles'] },
  { name: 'Lord Shiva Abhishekam', category: 'Abhishekam', price: 1100, duration: '1.5 hours', description: 'Sacred bathing of Lord Shiva with milk, yogurt, honey, panchamrita and rose water while chanting Rudra mantras.', significance: 'Symbolically cleanses the idol representing physical, mental and spiritual purity.', benefits: ['Physical mental and spiritual purification', 'Removes negative karma', 'Grants health and prosperity'] },
  { name: 'Sri Anjaneya Abhishekam', category: 'Abhishekam', price: 1100, duration: '1.5 hours', description: 'Bathing of Lord Anjaneya with sacred liquids while chanting Hanuman mantras.', significance: 'Pleases Lord Hanuman who blesses with strength and protection.', benefits: ['Strength and courage', 'Protection from evil', 'Removal of obstacles'] },
  { name: 'Sri Vighneswara Abhishekam', category: 'Abhishekam', price: 1100, duration: '1.5 hours', description: 'Sacred bathing of Lord Ganesha with panchamrita and sacred liquids.', significance: 'Lord Ganesha removes all obstacles when pleased with Abhishekam.', benefits: ['Removes all obstacles', 'Grants success', 'Auspicious beginnings'] },
  { name: 'Sri Venkateswara Swamy Abhishekam', category: 'Abhishekam', price: 1500, duration: '2 hours', description: 'Sacred bathing of Lord Venkateswara with milk, honey and sacred liquids.', significance: 'Lord Venkateswara blesses with immense wealth and fulfillment of wishes.', benefits: ['Fulfillment of wishes', 'Wealth and prosperity', 'Liberation from sins'] },
  { name: 'Navagraha Abhishekam', category: 'Abhishekam', price: 1500, duration: '2 hours', description: 'Abhishekam to all nine planets to remove planetary doshas from horoscope.', significance: 'Removes all planetary doshas and brings harmony to life.', benefits: ['Removes all planetary doshas', 'Career success', 'Health and harmony'] },
  { name: 'Sri Lakshmi Puja', category: 'Regular', price: 2100, duration: '2 hours', description: 'Goddess Lakshmi puja performed to attain financial growth, wisdom and prosperity. Lord Vishnu is also worshipped.', significance: 'Performed during Diwali, Dhanteras and Fridays to attain financial stability.', whenToPerform: 'Diwali, Dhanteras and Fridays are considered auspicious.', benefits: ['Financial success', 'Eradicates evil forces', 'Nullifies planetary ill-effects'] },
  { name: 'Ganapathi Puja', category: 'Regular', price: 1100, duration: '1.5 hours', description: 'Lord Ganesha puja performed to remove hurdles and bring success. Performed before any auspicious event.', significance: 'Lord Ganesha grants Siddhi and Buddhi and removes all obstacles.', whenToPerform: 'Performed during beginning of any auspicious event and on Ganesh Chaturthi.', benefits: ['Removes financial troubles', 'Grants wisdom to students', 'Brings peace and prosperity'] },
  { name: 'Sri Durga Devi Puja', category: 'Regular', price: 1500, duration: '2 hours', description: 'Puja to Goddess Durga for protection from evil and negative forces.', benefits: ['Protection from evil', 'Grants power and courage', 'Removes negativity'] },
  { name: 'Sri Saraswathi Devi Puja', category: 'Regular', price: 1500, duration: '2 hours', description: 'Puja to Goddess Saraswathi for excellence in studies, arts and career.', benefits: ['Excellence in studies', 'Success in arts', 'Wisdom and knowledge'] },
  { name: 'Mruthyunjaya Maha Puja', category: 'Special', price: 5100, duration: '3 hours', description: 'Most significant Japam representing Lord Shiva. Maha Mrithyunjaya means Victory over death.', significance: 'Maha Mrithyunjaya mantra represents victory over death and is the most powerful Shiva mantra.', benefits: ['Victory over death', 'Removes serious illness', 'Grants longevity and health'] },
  { name: 'Sahasra Lingarchana', category: 'Special', price: 7500, duration: '4 hours', description: 'Unique ritual to worship Lord Shiva by organizing 1116 lingas as kailasha prastharam.', significance: 'Said to give results equivalent to any pilgrimage. Invokes Shiva Shakti into every lingam.', benefits: ['Equivalent to pilgrimage', 'Health wealth and prosperity', 'Spiritual liberation'] },
  { name: 'Rudhrabhishekam', category: 'Special', price: 3100, duration: '2.5 hours', description: 'Powerful puja to Lord Shiva in Rudra form. Rudra suktham is chanted to the Shiva linga.', significance: 'Removes negative doshas and evil forces. Shiva linga worshipped with Panchamrith.', whenToPerform: 'Date fixed as per birth star. Shravana and Karthika months are auspicious.', benefits: ['Removes bad doshas', 'Eradicates evil forces', 'Nullifies negative effects of moon'] },
  { name: 'Kalasarpa Dosha Nivarana Puja', category: 'Special', price: 4100, duration: '3 hours', description: 'Puja to remove Kala Sarpa Dosha. Best performed on Amavasya falling on Wednesday.', significance: 'Removes hereditary Kalasarpa yoga dosha from horoscope.', whenToPerform: 'Amavasya day that falls on Wednesday is most auspicious.', benefits: ['Removes Kalasarpa dosha', 'Overcomes all life problems', 'Grants fortune and harmony'] },
  { name: 'Sri Rahu-Ketu Dosha Nivarana Puja', category: 'Special', price: 3100, duration: '2 hours', description: 'Puja to remove Rahu Ketu dosha that obstructs all good things in life.', significance: 'Removes all ill effects of Rahu and Ketu planets from horoscope.', whenToPerform: 'Monday is considered the best day to perform this puja.', benefits: ['Removes planetary ill effects', 'Removes obstacles', 'Grants success in all tasks'] },
  { name: 'Navagraha Dosha Nivarana Abhishekam', category: 'Special', price: 3500, duration: '2.5 hours', description: 'Performed to remove Navagraha Dosha based on horoscope. Nine planets are worshipped.', significance: 'Protects from all nine planetary doshas simultaneously.', benefits: ['Removes all planetary doshas', 'Cures health problems', 'Career success and prosperity'] },
  { name: 'Sri Sathyanarayana Vratham', category: 'Vratham', price: 2100, duration: '3 hours', description: 'Puja to Lord Vishnu performed on full moon day. Satyanarayana katha is recited. Rava Kesari is the main naivedyam.', significance: 'Lord Satyanarayana is the embodiment of truth. Bestows good health and wealth.', whenToPerform: 'Ekadashi, Pournami and Saturdays are auspicious. Also based on birth star.', benefits: ['Success in business and academics', 'Eradicates evil energies', 'Marks auspicious beginnings'] },
  { name: 'Sri Varalaxmi Vratham', category: 'Vratham', price: 2100, duration: '3 hours', description: 'Observed in Sravana month on Friday preceding full moon. Married women observe fasting till puja completion.', significance: 'Varalakshmi is goddess who gives all boons and wishes. Performed to acquire wealth.', whenToPerform: 'Shravana Fridays. Women should observe fasting till completion.', benefits: ['High financial status', 'Removes obstacles in life', 'Removes karmic issues and doshas'] },
  { name: 'Sri Kedareshwara Swamy Vratham', category: 'Vratham', price: 2100, duration: '3 hours', description: 'Performed on Bhadrapada Shukla. Generally performed for 21 days until Amavasya.', significance: 'Performed by Parvathi Devi to become part of Lord Shiva. Grants all wishes.', whenToPerform: 'Amavasya of Diwali season. Performed for 21 consecutive days.', benefits: ['All desires and wishes granted', 'Peace health and prosperity', 'Pleases Lord Shiva'] },
  { name: 'Sri Anantha Padmanabha Vratham', category: 'Vratham', price: 2100, duration: '3 hours', description: 'Puja to Lord Vishnu performed to regain lost prosperity and removal of sorrows.', significance: 'Lord Vishnu frequencies are very high on Ananth Chaturdashi day.', whenToPerform: '14th day of Bhadrapada month generally in September and October.', benefits: ['Regain lost prosperity', 'Relief from karmic difficulties', 'Happy married life'] },
  { name: 'Barasala Namakaranam', category: 'Ceremonies', price: 3500, duration: '2 hours', description: 'Naming ceremony for newborn baby performed on 11th day of birth as per shastras.', significance: 'Name should signify sex, fame, wealth and power. Mantras chanted for baby well-being.', whenToPerform: '11th day from birth. Can also be on 16th, 21st day, 3rd or 29th month.', benefits: ['Auspicious naming as per shastras', 'Baby well-being and health', 'Positive start to life'] },
  { name: 'Annaprasana', category: 'Ceremonies', price: 3500, duration: '2 hours', description: 'Ceremony when baby takes solid food for first time. Performed when baby is around 6 months old.', significance: 'Ensures child has good digestion and grows healthy and strong.', whenToPerform: '6th or 7th month on date compatible with birth star of child.', benefits: ['Good digestion and health', 'Strong growth for child', 'Cleansing of any illness'] },
  { name: 'Aksharabhyasam Vidhyarambham', category: 'Ceremonies', price: 3500, duration: '2 hours', description: 'Puja to Goddess Saraswathi to bestow wisdom and begin formal education.', significance: 'Bestows excellence in studies, arts and career. Removes stress related to education.', whenToPerform: 'Vasant Panchami and Navratris are most auspicious. Any Panchami thithi.', benefits: ['Excellence in academics', 'Wisdom in arts and music', 'Increased memory and concentration'] },
  { name: 'Upanayanam', category: 'Ceremonies', price: 5100, duration: '4 hours', description: 'Sacred thread ceremony allowing boy to study Vedas and enter Brahmacharya Avastha.', significance: 'Boy gains right to study Vedas. Three threads represent Brahma Vishnu and Shiva.', whenToPerform: 'When male child attains age of 8 years based on birth nakshatra muhurth.', benefits: ['Right to learn Vedas', 'Protection from evil spirits', 'Spiritual initiation'] },
  { name: 'Marriage Packages', category: 'Ceremonies', price: 15000, duration: 'Full day', description: 'Complete marriage ceremony including Snathakam, Mangala Gouri Puja, Mangalya Dharana and all traditional rituals.', significance: 'Sacred union performed as per Vedic traditions with all traditional ceremonies.', benefits: ['Auspicious sacred union', 'Blessings for long life', 'Prosperity for couple'] },
  { name: 'Muhurtham Puja', category: 'Ceremonies', price: 2100, duration: '1.5 hours', description: 'Puja performed during commencement of any project business or event for success and no roadblocks.', significance: 'Ensures success in new ventures and prevents obstacles during progress.', benefits: ['Success in new ventures', 'Removes roadblocks', 'Auspicious start'] },
  { name: 'Gruha Pravesham', category: 'Gruha', price: 5100, duration: '3 hours', description: 'Puja performed before moving into a new house to remove negative energy and bring good fortune.', significance: 'Removes negative energy from house. Compatible with Janma Nakshatra of wife.', whenToPerform: 'Magh, Falguna, Baishak, Jeshtha months are auspicious. Shukla Paksha period.', benefits: ['Removes negative energy', 'Protects future residents', 'Increases good fortune'] },
  { name: 'Bhumi Puja', category: 'Gruha', price: 3100, duration: '2 hours', description: 'Puja to Mother Earth and Vastu Purusha performed before starting construction on any land.', significance: 'Removes evil forces from land. Navagraha Puja and Vastu Puja are main aspects.', whenToPerform: 'Shravan, Kartik, Margshirsh and Paush months are most favorable.', benefits: ['Makes land fertile', 'Eradicates evil from land', 'Protects from natural calamities'] },
  { name: 'Vastu Puja', category: 'Gruha', price: 3500, duration: '2.5 hours', description: 'Ritual to worship Vastu Purush and correct faults of construction. Removes evil and negative vibes from home.', significance: 'Vastu Purush signifies power spirit and energy residing in the home.', benefits: ['Removes vastu doshas', 'Brings harmony and comfort', 'Eradicates negative forces'] },
  { name: 'Vasthu Shanti Puja', category: 'Gruha', price: 4100, duration: '3 hours', description: 'Puja to Vastu Purush the protector of house. Blesses house with harmony comfort and prosperity.', significance: 'Removes all Vastu doshas. Restores positivity and harmony to living space.', whenToPerform: 'Vastu time occurs maximum two times in a month.', benefits: ['Harmony and prosperity', 'Protection from natural calamities', 'Removes all negative forces'] },
  { name: 'Sri Ganapathi Homam', category: 'Homam', price: 3500, duration: '2.5 hours', description: 'Homam to Lord Ganesha performed before any auspicious activity or ceremony for removal of obstacles.', significance: 'Ganapathi is worshipped before any auspicious activity. Ashta Dravya and Durva grass are key ingredients.', whenToPerform: 'Sankashti Chaturthi and Vinayaka Chaturthi. Brahma Muhurth 4:30-6:00 AM.', benefits: ['Removes all obstacles', 'Remedy for Ketu Maha Dasa', 'Solves wealth related issues'] },
  { name: 'Sri Laxmi Ganapathi Homam', category: 'Homam', price: 4100, duration: '3 hours', description: 'Homam invoking both Goddess Lakshmi and Lord Ganesha for wealth and removal of obstacles.', significance: 'Lotus flowers offered to Agni for Goddess Lakshmi and Ganapathi Devudu.', whenToPerform: 'Fridays are most beneficial. Also as per janma nakshatra.', benefits: ['High financial status', 'Overcomes money related sorrows', 'Removes obstacles in life'] },
  { name: 'Navagraha Dosha Nivarana Homam', category: 'Homam', price: 5100, duration: '3 hours', description: 'Homam performed when planetary positions are inauspicious in horoscope. Nine grains are main ingredients.', significance: 'Protects from all nine planetary doshas present in horoscope.', benefits: ['Removes graha doshas', 'Cures health problems', 'Successful career and prosperity'] },
  { name: 'Vaasthu Homam', category: 'Homam', price: 4500, duration: '3 hours', description: 'Sacrifice performed usually before shifting into new home or office to bring peace and prosperity.', significance: 'Similar to Feng Shui. Pleases direction gods who bless occupants.', benefits: ['Brings positivity to new home', 'Removes negative energies', 'Prosperity and abundance'] },
  { name: 'Chandi Homam', category: 'Homam', price: 7500, duration: '4 hours', description: 'Homam to Goddess Chandi performed during Navratri. 13 unique ingredients for 13 chapters of Saptashati.', significance: 'Eliminates all negative energies. All Nava Grahas are invoked simultaneously.', whenToPerform: 'Navratri, Ashtami, Navami, Chaturdasi, Amavasya and Pournami are auspicious.', benefits: ['Removes all obstacles and sufferings', 'Nullifies planetary influences', 'Removes evil eyes and curses'] },
  { name: 'Kuja Dosha Nivarana Homam', category: 'Homam', price: 4100, duration: '3 hours', description: 'Homam to remove Manglik dosha related to placement of Planet Mars in horoscope.', significance: 'Nullifies negative effects of Mars when placed in 2nd 4th 7th 8th or 12th houses.', benefits: ['Removes marriage hindrances', 'Nullifies manglik dosha', 'Blesses with harmonious marriage'] },
  { name: 'Sri Sudharshana Homam', category: 'Homam', price: 5100, duration: '3 hours', description: 'Powerful homam to Lord Sudarshana for protection from enemies and evil. White mustard and 108 herbs used.', significance: 'Bestows Lord Vishnu protection. Performed on Ekadasi Dwadasi and Pournima.', whenToPerform: 'Saturdays Ekadasi and Pournami are most auspicious.', benefits: ['Protection from enemies', 'Cures health problems', 'Removes evil spirits and black magic'] },
  { name: 'Pasupatha Homam', category: 'Homam', price: 5500, duration: '3.5 hours', description: 'Homam to remove obstacles and negativity. Multiple types available for different remedies including marriage dosha, career and health.', significance: 'Powerful remedy for various life challenges including marriage career and health issues.', benefits: ['Removes marriage obstacles', 'Career promotions', 'Removes Kalasarpa dosha'] },
  { name: 'Sri Rahu-Ketu Dosha Nivarana Homam', category: 'Homam', price: 4100, duration: '3 hours', description: 'Homam to remove Rahu Ketu dosha causing Kala Sharpa Yoga in horoscope.', significance: 'Removes all ill effects of Rahu Ketu that obstruct good things in life.', whenToPerform: 'Monday is considered the best day to perform this homam.', benefits: ['Removes planetary ill effects', 'Removes roadblocks', 'Grants success in all tasks'] },
];

mongoose.connect(process.env.MONGO_URI).then(async () => {
  console.log('Connected to MongoDB');
  await Puja.deleteMany({});
  console.log('Cleared existing pujas');
  const result = await Puja.insertMany(pujas);
  console.log('Inserted ' + result.length + ' pujas successfully!');
  process.exit(0);
}).catch(err => { console.error(err.message); process.exit(1); });
